name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Add build steps here (minification, compression, etc.)

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure build finishes before deployment
    if: github.ref == 'refs/heads/main'  # Only deploy on push to main branch

    steps:
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.DEPLOY_DOMAIN }} >> ~/.ssh/known_hosts  # Use a secret for domain

      - name: Deploy to Server
        run: |
          scp -r ./andrea-genovese/* andrea@${{ secrets.DEPLOY_DOMAIN }}:/home/andrea/public_html/

          # Add additional deployment steps (service restart, permission management, etc.) based on your server setup